mysite/famleague/urls.py
from django.urls import path

from . import views


app_name = 'famleague'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login_view'),
    path('login_user/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('register_user', views.register_user, name='register_user'),
    path('rules/', views.rules, name='rules'),
    path('leader/', views.leader, name='leader'),
    path('lineup/<str:category>/', views.lineup, name='lineup'),
    path('pick_team/<int:team_id>/', views.pick_team, name='pick_team')

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('famleague.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/famleague/models.py
from django.db import models


from django.contrib.auth.models import User


class Team(models.Model):
    name = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images/')
    category = models.CharField(max_length=1)
    score_2017 = models.IntegerField()
    score_2018 = models.IntegerField()
    score_2019 = models.IntegerField()
    users = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return self.name


# class GameScore(models.Model):
#     teamA = models.ForeignKey(Team, on_delete=models.PROTECT)
#     teamB = models.ForeignKey(Team, on_delete=models.PROTECT)
#     date = models.DateTimeField()
#     score = models.IntegerField()
#
#     def __str__(self):
#         return self.teamA

mysite/famleague/views.py
from django.shortcuts import render, reverse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from .models import Team
# from . models import TeamScore

from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    teams = request.user.team_set.all().order_by('category')
    user_teams = {'teams': teams}
    return render(request, 'famleague/index.html', user_teams)

def login_view(request):
    return render(request, 'famleague/login.html')

# receives the form submission
def login_user(request):
    # retrieve the variables from the form submission
    username = request.POST['username'].capitalize()
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse('famleague:index'))
    else:
        return HttpResponseRedirect(reverse('famleague:login_view'))


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('famleague:login_view'))



def register_user(request):
    username = request.POST['username'].capitalize()
    email = request.POST['email']
    password = request.POST['password']
    user = User.objects.create_user(username, email, password)
    login(request, user)
    return HttpResponseRedirect(reverse('famleague:rules'))



@login_required
def rules(request):
    return render(request, 'famleague/rules.html')


@login_required
def lineup(request, category):
    teams = Team.objects.filter(category=category).order_by('-score_2018')
    user_team_ids = set(request.user.team_set.values_list('id', flat=True))
    user_teams = {'teams': teams, 'user_team_ids': user_team_ids, 'category': category}
    return render(request, 'famleague/lineup.html', user_teams)


@login_required
def pick_team(request, team_id):
    # look up the team with that id
    team = Team.objects.get(pk=team_id)
    user = request.user
    for one_team in user.team_set.all():
        if one_team.category == team.category:
            # one_team.users.remove(user)
            user.team_set.remove(one_team)

    team.users.add(user)

    url = ''
    if team.category == 'A':
        url = reverse('famleague:lineup', kwargs={'category': 'B'})
    if team.category == 'B':
        url = reverse('famleague:lineup', kwargs={'category': 'C'})
    if team.category == 'C':
        url = reverse('famleague:lineup', kwargs={'category': 'D'})
    if team.category == 'D':
        url = reverse('famleague:index')
    return HttpResponseRedirect(url)


@login_required
def leader(request):
    # get all the teams
    teams = Team.objects.all()
    # create a score list
    team_scores = []
    # iterate over the teams and create a dictionary for table
    for team in teams:
        team_scores.append({
            'team': team.name,
            'score': team.score_2019,
            'category': team.category
        })
    team_scores.sort(key=lambda x: x['score'], reverse=True)
    team_scores.sort(key=lambda x: x['category'])

    # get all the users
    users = User.objects.all()
    user_scores = []
    # iterate over users
    for user in users:
        user_score = 0
        for team in user.team_set.all():
            user_score += team.score_2019
        user_scores.append({'username': user.username, 'score': user_score})
    user_scores.sort(key=lambda x: x['score'], reverse=True)

    context = {'user_scores': user_scores, 'team_scores': team_scores}
    return render(request, 'famleague/leader.html', context)

# @login_required
# def message(request):
#

mysite/famleague/templates/famleague/chat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>🏈 FamLeague 🏈</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'famleague/chat.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'famleague/navigation.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Monoton|Open+Sans" rel="stylesheet">
</head>
<body>
    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a href="{% url 'famleague:index' %}">Your Team</a>
      <a href="{% url 'famleague:rules' %}">How to Play</a>
      <a href="{% url 'famleague:lineup' 'A' %}">Pick Lineup</a>
      <a href="{% url 'famleague:leader' %}">Leaderboard</a>
      <!--<a href="{% url 'famleague:chat' %}">Chatter Box</a>  -->
      <a href="{% url 'famleague:logout_user' %}">Logout</a>

    </div>
    <header><span id="menu" style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span></header>
    <div id="main-flex-chat">
        <h1>The Chatter Box</h1>

        <form action="{% url 'famleague:message' %}" method="post" >
        {% csrf_token %}
        <input type="text" name="message" placeholder="enter message here">
        <button class="btn" type="submit">Submit</button>
        </form>





    </div>



    <!-- Footer -->
    <footer>
        <p>Angelina Bowmer, Inc. ©</p>
    </footer>

    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
        }
    </script>

</body>
</html>

mysite/famleague/templates/famleague/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>🏈 FamLeague 🏈</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'famleague/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'famleague/navigation.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Monoton|Open+Sans" rel="stylesheet">
</head>
<body>
    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a href="{% url 'famleague:index' %}">Your Team</a>
      <a href="{% url 'famleague:rules' %}">How to Play</a>
      <a href="{% url 'famleague:lineup' 'A' %}">Pick Lineup</a>
      <a href="{% url 'famleague:leader' %}">Leaderboard</a>
      <a href="{% url 'famleague:logout_user' %}">Logout</a>

    </div>
    <header><span id="menu" style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span></header>
    <div id="main-user-page">

        <h2>Welcome, {{user}}!</h2>
        <h3>Your Team Lineup</h3>
        <div class="lineup">
            {% for team in teams %}
            <div class="user-lineup">
                <img src="{{team.image.url}}">
                <p>{{team.city}} {{team.name}}</p>
                <p>Score: {{team.score_2019}}</p>
             </div>
            {% endfor %}

        </div>
     <!-- Footer -->
        <footer>
            <p>Angelina Bowmer, Inc. ©</p>
        </footer>
    </div>



    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
        }
    </script>

</body>
</html>

mysite/famleague/templates/famleague/leader.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>🏈 FamLeague 🏈</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'famleague/leader.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'famleague/navigation.css' %}" />
</head>
<body>
    <header><span id="menu" style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span></header>


    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a href="{% url 'famleague:index' %}">Your Team</a>
      <a href="{% url 'famleague:rules' %}">How to Play</a>
      <a href="{% url 'famleague:lineup' 'A' %}">Pick Lineup</a>
      <a href="{% url 'famleague:leader' %}">Leaderboard</a>
      <!--<a href="{% url 'famleague:chat' %}">Chatter Box</a>  -->
      <a href="{% url 'famleague:logout_user' %}">Logout</a>

    </div>
    <h2>Leaderboard</h2>
    <div id="main-leader-content">

        <div class="lead-board">
            <table>
                <tr>
                    <th>Place</th>
                    <th>Name</th>
                    <th>Score</th>
                </tr>
                {% for user_score in user_scores %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{user_score.username}}</td>
                    <td>{{user_score.score}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="team-board">
            <table>
                <tr>
                    <th>Team Name</th>
                    <th>Score</th>
                    <th>Category</th>
                </tr>
                {% for team_score in team_scores %}
                <tr>
                    <td>{{team_score.team}}</td>
                    <td>{{team_score.score}}</td>
                    <td>{{team_score.category}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>

    </div>
    <!-- Footer -->
        <footer>
            <p>Angelina Bowmer, Inc. ©</p>
        </footer>
    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
        }
    </script>
</body>
</html>

mysite/famleague/templates/famleague/lineup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>🏈 FamLeague 🏈</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'famleague/lineup.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'famleague/navigation.css' %}" />
</head>
<body>
    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a href="{% url 'famleague:index' %}">Your Team</a>
      <a href="{% url 'famleague:rules' %}">How to Play</a>
      <a href="{% url 'famleague:lineup' 'A' %}">Pick Lineup</a>
      <a href="{% url 'famleague:leader' %}">Leaderboard</a>
      <!--<a href="{% url 'famleague:chat' %}">Chatter Box</a>  -->
      <a href="{% url 'famleague:logout_user' %}">Logout</a>
    </div>
    <header><span id="menu" style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span></header>


        <div class="teams">
            <h2>Create Your Lineup</h2> <h3>{{category}}</h3>
            <center><p class="how-to">Pick a team from each category, once you have made your selection the team will be placed in the "Your Team" page. </p></center>

            <button id="a_team_bt" class="btn-cat">A</button>
            <button id="b_team_bt" class="btn-cat">B</button>
            <button id="c_team_bt" class="btn-cat">C</button>
            <button id="d_team_bt" class="btn-cat">D</button>

            <form method="post" id="main-flex-lineup">
                {% csrf_token %}
                {% for team in teams %}
                <div class="team">
                    <button type="submit" class="btn" formaction="{% url 'famleague:pick_team' team.id %}">
                        <img {% if team.id not in user_team_ids %}class="teampick"{% endif %} src="{{team.image.url}}">
                    </button>
                    <p> {{team.city}} {{team.name}}</p>

                </div>
                {% endfor %}
            </form>

        </div>
         <!-- Footer -->
        <footer>
            <p>Angelina Bowmer, Inc. ©</p>
        </footer>









    <script>

        let a_team_bt = document.querySelector('#a_team_bt')
        a_team_bt.onclick = function() {
            window.location = "{% url 'famleague:lineup' 'A' %}"
        }
        let b_team_bt = document.querySelector('#b_team_bt')
        b_team_bt.onclick = function() {
            window.location = "{% url 'famleague:lineup' 'B' %}"
        }
        let c_team_bt = document.querySelector('#c_team_bt')
        c_team_bt.onclick = function() {
            window.location = "{% url 'famleague:lineup' 'C' %}"
        }
        let d_team_bt = document.querySelector('#d_team_bt')
        d_team_bt.onclick = function() {
            window.location = "{% url 'famleague:lineup' 'D' %}"
        }


        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
        }
    </script>

</body>
</html>

mysite/famleague/templates/famleague/login.html
<!DOCTYPE html>
<html lang="en">
<head>

    <title>🏈 FamLeague 🏈</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'famleague/login.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Monoton|Open+Sans" rel="stylesheet">

</head>
<body>
    <div id="main-flex-container">
        <h1>FamLeague</h1>
            <div class="form-box">
                <div class="left-container">




                    <div class="form">
                    <form action="{% url 'famleague:login_user' %}" method="post" class="login-form">
                    {% csrf_token %}
                        <table>
                            <h2>Login</h2>
                            <tr>
                            <td><label class="lbl">Username</label></td>
                            <td><input type="text" name="username" placeholder="Username"></td>
                            </tr>

                            <tr>
                            <td><label class="lbl">Password</label></td>
                            <td><input type="password" name="password" placeholder="Password"></td>
                            </tr>

                        </table>
                        <button type="submit" class="login-btn">Sign in</button>
                    </form>

                    </div>

                </div>

                <div class="right-container">




                        <div class="form">
                        <form action="{% url 'famleague:register_user' %}" method="post" class="registration-form">
                        {% csrf_token %}
                                <table>
                                    <h2>Register</h2>
                                        <tr>
                                        <td><label class="lbl" >Username</label></td>
                                        <td><input type="text" name="username" placeholder="Username"></td>
                                        </tr>

                                        <tr>
                                        <td><label class="lbl" >Password</label></td>
                                        <td><input type="password" name="password" placeholder="Password"></td>
                                        </tr>

                                        <tr>
                                        <td><label class="lbl">Email</label></td>
                                        <td><input type="text" name="email" placeholder="Email"></td>
                                        </tr>
                                </table>
                            <button type="submit" class="login-btn">Sign me up</button>
                        </form>

                        </div>
                </div>

        </div>


        <!-- Footer -->
        <footer>
            <p>Angelina Bowmer, Inc. ©</p>
        </footer>
    </div>







</body>
</html>

mysite/famleague/templates/famleague/rules.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>🏈 FamLeague 🏈</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'famleague/rules.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'famleague/navigation.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Monoton" rel="stylesheet">
</head>
<body>
    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a href="{% url 'famleague:index' %}">Your Team</a>
      <a href="{% url 'famleague:lineup' 'A' %}">Pick Lineup</a>
      <a href="{% url 'famleague:leader' %}">Leaderboard</a>
      <!--<a href="{% url 'famleague:chat' %}">Chatter Box</a>  -->
      <a href="{% url 'famleague:logout_user' %}">Logout</a>

    </div>
        <header><span id="menu" style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span></header>
    <div id="main-rules">

        <h1>How To Play</h1>

        <p class="rules">
        <h4>This is a regular season game, starting week 1 and ending week 17.</h4>
        <u>Directions:</u>
        Each player will pick a team from column A, B, C and D.</p>

        <p class="rules"> <u>Entry Terms:</u>
                Each four team combos can be had once, first come first serve. No changing pick's after submitting your selection. Entry's accepted starting August 1st through til the start of the regular season in September.</p>
        <p class="rules"><u>Prizes:</u>
            Last place will get 15 points to carry into next season, the top three will be the winners.
        </p>
            <h3>Scoring</h3>
            <ul>
                <li>Win = 2 points</li>
                <li>Tie = 1 points</li>
                <li>Playoff Berth = 2 points</li>
            </ul>

        <input id="cb_agree" type="checkbox"/>I agree to the rules stated above
        <button id="bt_agree" disabled>Next</button>


    </div>
    <!-- Footer -->
    <footer>
            <p>Angelina Bowmer, Inc. ©</p>
    </footer>


    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
        }

        let cb_agree = document.querySelector('#cb_agree')
        let bt_agree = document.querySelector('#bt_agree')
        cb_agree.onchange = function() {
            if (cb_agree.checked) {
                bt_agree.removeAttribute('disabled')
            } else {
                bt_agree.setAttribute('disabled', 'disabled')
            }
        }
        bt_agree.onclick = function() {
            window.location = "{% url 'famleague:lineup' 'A' %}"
        }
    </script>


</body>
</html>